import type { Metadata } from "next";
import { LegalLayout, LegalList, LegalSection } from "@/components/legal/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — Random Knowledge",
  description: "The terms that govern your use of Random Knowledge.",
};

const EFFECTIVE_DATE = "September 9, 2026";
const CONTACT_EMAIL = "jason@astrojason.com";

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" effectiveDate={EFFECTIVE_DATE}>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your use of Random Knowledge at{" "}
        <span className="font-medium text-fg-strong">random-knowledge.astrojason.com</span>{" "}
        (&ldquo;the app&rdquo;), operated by Jason Sylvester (&ldquo;we,&rdquo; &ldquo;us&rdquo;).
        By signing in and using the app, you agree to these Terms. If you don&apos;t agree, please
        don&apos;t use the app.
      </p>

      <LegalSection heading="The service">
        <p>
          Random Knowledge delivers one short, AI-generated lesson per day along with a short
          multiple-choice comprehension quiz, and tracks your streak and progress over time.
          Lesson content is generated by a third-party AI model and, while we aim for accuracy, it
          may occasionally contain errors, omissions, or oversimplifications. Don&apos;t rely on it
          as a sole source for medical, legal, financial, or other professional decisions.
        </p>
      </LegalSection>

      <LegalSection heading="Access and eligibility">
        <p>
          Random Knowledge is invite-only. Signing in with Google creates an access request, which
          must be approved before you can use the app. We may approve, deny, or revoke access to
          the app at our discretion, at any time, for any reason, including inactivity or misuse.
        </p>
        <p>
          You must be at least 13 years old to use the app. You are responsible for maintaining the
          security of the Google account you use to sign in.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>You agree not to:</p>
        <LegalList
          items={[
            "Attempt to circumvent access controls or the app's usage limits",
            "Use the app to generate, extract, or republish content at scale (e.g., scraping)",
            "Interfere with or disrupt the app's operation or the infrastructure it relies on",
            "Use the app for any unlawful purpose",
          ]}
        />
      </LegalSection>

      <LegalSection heading="Content and intellectual property">
        <p>
          Lesson text and quiz questions are generated using a third-party AI model based on
          prompts we control; we do not independently verify each lesson&apos;s factual accuracy.
          The app&apos;s design, code, and branding belong to us. Generated lesson content is provided for
          your personal, non-commercial use.
        </p>
      </LegalSection>

      <LegalSection heading="Disclaimer of warranties">
        <p>
          The app is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without
          warranties of any kind, express or implied, including warranties of accuracy,
          merchantability, fitness for a particular purpose, or non-infringement. We do not
          guarantee the app will be uninterrupted, error-free, or available at all times.
        </p>
      </LegalSection>

      <LegalSection heading="Limitation of liability">
        <p>
          To the fullest extent permitted by law, we are not liable for any indirect, incidental,
          or consequential damages arising from your use of, or inability to use, the app,
          including reliance on any lesson content. The app is a personal project offered free of
          charge, without any service-level commitment.
        </p>
      </LegalSection>

      <LegalSection heading="Termination">
        <p>
          We may suspend or revoke your access to the app at any time, with or without notice. You
          may stop using the app at any time by signing out and, if you wish, revoking Random
          Knowledge&apos;s access to your Google account from your Google Account settings.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to these Terms">
        <p>
          We may update these Terms from time to time. If we make material changes, we will update
          the effective date above. Continued use of the app after a change constitutes acceptance
          of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>
          Questions about these Terms can be sent to{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-accent hover:opacity-85">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
