import { createFirestoreApi } from "@random-knowledge/shared/firestore";
import { db } from "@/lib/firebase";

export const {
  getStreak,
  getWeights,
  setWeights,
  getSelectedCategories,
  setSelectedCategories,
  getHistory,
  appendHistory,
  getLesson,
  setLesson,
  getProgress,
  completeDailyLesson,
  recordAccessRequest,
  getAccessRequest,
  listAccessRequests,
  grantAccess,
  revokeAccess,
  listGenerationLog,
  listCronRunLog,
  createShare,
  getShare,
  addToStash,
  getStashEntry,
  getStash,
  removeFromStash,
  resetAllUserData,
} = createFirestoreApi(db);
